name: Build and Notify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13' # Specify the Node.js version you need

    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: ng build
      # This now should work as Angular CLI is installed globally
        
    - name: Check Build Success
      if: failure() # This step will run only if the previous step fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com
        server_port: 587
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        
        # EMAIL_USERNAME(zutrzuturztfuztfu@outlook.com)
        # EMAIL_PASSWORD(@igcdkzudsagdi)
        

        subject: Build Failed
        body: The production build failed. Please check the GitHub Actions logs for more details.
        to: khaled.maati@accenture.com
        from: GitHub Actions <noreply@github.com>
